/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rs_polars_api_Polars */

#ifndef _Included_rs_polars_api_Polars
#define _Included_rs_polars_api_Polars
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rs_polars_api_Polars
 * Method:    fromCSV
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_rs_polars_api_Polars_fromCSV
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
