/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rs_polars_api_DataFrame */

#ifndef _Included_rs_polars_api_DataFrame
#define _Included_rs_polars_api_DataFrame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rs_polars_api_DataFrame
 * Method:    print
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_rs_polars_api_DataFrame_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
